### 导入包

In [85]:
# 导入必要的包 numpy、pandas以及scikit-learn归一化预处理
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

### 读取文件

In [86]:
# 指定相对路径
path = './data/'

In [87]:
# 利用 pands 进行读取文件操作
train = pd.read_csv(path + 'train.csv', engine='python', encoding='Big5')
test = pd.read_csv(path + 'test.csv', engine='python', encoding='gbk')

In [88]:
train

,Date,stations,observation,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,2014/1/1,豐原,AMB_TEMP,14,14,14,13,12,12,12,...,22,22,21,19,17,16,15,15,15,15
1,2014/1/1,豐原,CH4,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
2,2014/1/1,豐原,CO,0.51,0.41,0.39,0.37,0.35,0.3,0.37,...,0.37,0.37,0.47,0.69,0.56,0.45,0.38,0.35,0.36,0.32
3,2014/1/1,豐原,NMHC,0.2,0.15,0.13,0.12,0.11,0.06,0.1,...,0.1,0.13,0.14,0.23,0.18,0.12,0.1,0.09,0.1,0.08
4,2014/1/1,豐原,NO,0.9,0.6,0.5,1.7,1.8,1.5,1.9,...,2.5,2.2,2.5,2.3,2.1,1.9,1.5,1.6,1.8,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4315,2014/12/20,豐原,THC,1.8,1.8,1.8,1.8,1.8,1.7,1.7,...,1.8,1.8,2,2.1,2,1.9,1.9,1.9,2,2
4316,2014/12/20,豐原,WD_HR,46,13,61,44,55,68,66,...,59,308,327,21,100,109,108,114,108,109
4317,2014/12/20,豐原,WIND_DIREC,36,55,72,327,74,52,59,...,18,311,52,54,121,97,107,118,100,105
4318,2014/12/20,豐原,WIND_SPEED,1.9,2.4,1.9,2.8,2.3,1.9,2.1,...,2.3,2.6,1.3,1,1.5,1,1.7,1.5,2,2
4319,2014/12/20,豐原,WS_HR,0.7,0.8,1.8,1,1.9,1.7,2.1,...,1.3,1.7,0.7,0.4,1.1,1.4,1.3,1.6,1.8,2

In [89]:
test

        id_0    AMB_TEMP    15    14  14.1    13  13.1  13.2  13.3  13.4    12
0       id_0         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
1       id_0          CO  0.36  0.35  0.34  0.33  0.33  0.34  0.34  0.37  0.42
2       id_0        NMHC  0.11  0.09  0.09   0.1   0.1   0.1   0.1  0.11  0.12
3       id_0          NO   0.6   0.4   0.3   0.3   0.3   0.7   0.8   0.8   0.9
4       id_0         NO2   9.3   7.1   6.1   5.7   5.5   5.3   5.5   7.1   7.5
...      ...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
4314  id_239         THC   1.8   1.8   1.8   1.8   1.7   1.8   2.1     2   2.5
4315  id_239       WD_HR   105   105   110    99   101   104    82    59   256
4316  id_239  WIND_DIREC   108   107   103    89    85   104    82   303   268
4317  id_239  WIND_SPEED   1.4   1.7   1.9   1.7   1.6   1.4   0.6   0.8   1.2
4318  id_239       WS_HR   1.4   1.7   1.6   1.8   1.8   1.6   0.6   0.5   0.5

[4319 rows x 11 columns]

In [90]:
# 删除无关特征
train = train.drop(['Date', 'stations', 'observation'], axis=1)
# 删除前两列
test_x = test.iloc[:, 2:]

In [91]:
train

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,14,14,14,13,12,12,12,12,15,17,...,22,22,21,19,17,16,15,15,15,15
1,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
2,0.51,0.41,0.39,0.37,0.35,0.3,0.37,0.47,0.78,0.74,...,0.37,0.37,0.47,0.69,0.56,0.45,0.38,0.35,0.36,0.32
3,0.2,0.15,0.13,0.12,0.11,0.06,0.1,0.13,0.26,0.23,...,0.1,0.13,0.14,0.23,0.18,0.12,0.1,0.09,0.1,0.08
4,0.9,0.6,0.5,1.7,1.8,1.5,1.9,2.2,6.6,7.9,...,2.5,2.2,2.5,2.3,2.1,1.9,1.5,1.6,1.8,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4315,1.8,1.8,1.8,1.8,1.8,1.7,1.7,1.8,1.8,1.8,...,1.8,1.8,2,2.1,2,1.9,1.9,1.9,2,2
4316,46,13,61,44,55,68,66,70,66,85,...,59,308,327,21,100,109,108,114,108,109
4317,36,55,72,327,74,52,59,83,106,105,...,18,311,52,54,121,97,107,118,100,105
4318,1.9,2.4,1.9,2.8,2.3,1.9,2.1,3.7,2.8,3.8,...,2.3,2.6,1.3,1,1.5,1,1.7,1.5,2,2
4319,0.7,0.8,1.8,1,1.9,1.7,2.1,2,2,1.7,...,1.3,1.7,0.7,0.4,1.1,1.4,1.3,1.6,1.8,2

In [92]:
train[train == 'NR'] = 0
test[test == 'NR'] = 0

In [93]:
test_x

        15    14  14.1    13  13.1  13.2  13.3  13.4    12
0      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
1     0.36  0.35  0.34  0.33  0.33  0.34  0.34  0.37  0.42
2     0.11  0.09  0.09   0.1   0.1   0.1   0.1  0.11  0.12
3      0.6   0.4   0.3   0.3   0.3   0.7   0.8   0.8   0.9
4      9.3   7.1   6.1   5.7   5.5   5.3   5.5   7.1   7.5
...    ...   ...   ...   ...   ...   ...   ...   ...   ...
4314   1.8   1.8   1.8   1.8   1.7   1.8   2.1     2   2.5
4315   105   105   110    99   101   104    82    59   256
4316   108   107   103    89    85   104    82   303   268
4317   1.4   1.7   1.9   1.7   1.6   1.4   0.6   0.8   1.2
4318   1.4   1.7   1.6   1.8   1.8   1.6   0.6   0.5   0.5

[4319 rows x 9 columns]

#### 把0~8列作为训练集，第九列作为测试集

In [94]:
train_x = []
train_y = []

In [95]:
for i in range(15):
    x = train.iloc[:, i:i + 9]
    # notice if we don't set columns name, it will have different columns name in each iteration
    x.columns = np.array(range(9))
    y = train.iloc[:, i + 9]
    y.columns = np.array(range(1))
    train_x.append(x)
    train_y.append(y)

In [96]:
train_x

[         0     1     2     3     4     5     6     7     8
 0       14    14    14    13    12    12    12    12    15
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.51  0.41  0.39  0.37  0.35   0.3  0.37  0.47  0.78
 3      0.2  0.15  0.13  0.12  0.11  0.06   0.1  0.13  0.26
 4      0.9   0.6   0.5   1.7   1.8   1.5   1.9   2.2   6.6
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8   1.8   1.8   1.7   1.7   1.8   1.8
 4316    46    13    61    44    55    68    66    70    66
 4317    36    55    72   327    74    52    59    83   106
 4318   1.9   2.4   1.9   2.8   2.3   1.9   2.1   3.7   2.8
 4319   0.7   0.8   1.8     1   1.9   1.7   2.1     2     2

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       14    14    13    12    12    12    12    15    17
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.41  0.39  0.37  0.35   0.3  0.37  0.47  0.78  0.74
 3     0.15  0.13  0.12  0.11  0.06   0.1  0.13  0.26  0.23
 4      0.6   0.5   1.7   1.8   1.5   1.9   2.2   6.6   7.9
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8   1.8   1.7   1.7   1.8   1.8   1.8
 4316    13    61    44    55    68    66    70    66    85
 4317    55    72   327    74    52    59    83   106   105
 4318   2.4   1.9   2.8   2.3   1.9   2.1   3.7   2.8   3.8
 4319   0.8   1.8     1   1.9   1.7   2.1     2     2   1.7

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       14    13    12    12    12    12    15    17    20
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.39  0.37  0.35   0.3  0.37  0.47  0.78  0.74  0.59
 3     0.13  0.12  0.11  0.06   0.1  0.13  0.26  0.23   0.2
 4      0.5   1.7   1.8   1.5   1.9   2.2   6.6   7.9   4.2
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8   1.7   1.7   1.8   1.8   1.8   1.8
 4316    61    44    55    68    66    70    66    85    67
 4317    72   327    74    52    59    83   106   105    60
 4318   1.9   2.8   2.3   1.9   2.1   3.7   2.8   3.8   4.1
 4319   1.8     1   1.9   1.7   2.1     2     2   1.7     3

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       13    12    12    12    12    15    17    20    22
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.37  0.35   0.3  0.37  0.47  0.78  0.74  0.59  0.52
 3     0.12  0.11  0.06   0.1  0.13  0.26  0.23   0.2  0.18
 4      1.7   1.8   1.5   1.9   2.2   6.6   7.9   4.2   2.9
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.7   1.7   1.8   1.8   1.8   1.8   1.8
 4316    44    55    68    66    70    66    85    67    60
 4317   327    74    52    59    83   106   105    60    62
 4318   2.8   2.3   1.9   2.1   3.7   2.8   3.8   4.1   3.2
 4319     1   1.9   1.7   2.1     2     2   1.7     3   2.9

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       12    12    12    12    15    17    20    22    22
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.35   0.3  0.37  0.47  0.78  0.74  0.59  0.52  0.41
 3     0.11  0.06   0.1  0.13  0.26  0.23   0.2  0.18  0.12
 4      1.8   1.5   1.9   2.2   6.6   7.9   4.2   2.9   3.4
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.7   1.7   1.8   1.8   1.8   1.8   1.8   1.8
 4316    55    68    66    70    66    85    67    60    61
 4317    74    52    59    83   106   105    60    62    58
 4318   2.3   1.9   2.1   3.7   2.8   3.8   4.1   3.2   3.1
 4319   1.9   1.7   2.1     2     2   1.7     3   2.9   2.7

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       12    12    12    15    17    20    22    22    22
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2      0.3  0.37  0.47  0.78  0.74  0.59  0.52  0.41   0.4
 3     0.06   0.1  0.13  0.26  0.23   0.2  0.18  0.12  0.11
 4      1.5   1.9   2.2   6.6   7.9   4.2   2.9   3.4     3
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.7   1.7   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 4316    68    66    70    66    85    67    60    61    60
 4317    52    59    83   106   105    60    62    58    75
 4318   1.9   2.1   3.7   2.8   3.8   4.1   3.2   3.1   2.8
 4319   1.7   2.1     2     2   1.7     3   2.9   2.7   2.8

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       12    12    15    17    20    22    22    22    22
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.37  0.47  0.78  0.74  0.59  0.52  0.41   0.4  0.37
 3      0.1  0.13  0.26  0.23   0.2  0.18  0.12  0.11   0.1
 4      1.9   2.2   6.6   7.9   4.2   2.9   3.4     3   2.5
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.7   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 4316    66    70    66    85    67    60    61    60    59
 4317    59    83   106   105    60    62    58    75    18
 4318   2.1   3.7   2.8   3.8   4.1   3.2   3.1   2.8   2.3
 4319   2.1     2     2   1.7     3   2.9   2.7   2.8   1.3

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       12    15    17    20    22    22    22    22    22
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.47  0.78  0.74  0.59  0.52  0.41   0.4  0.37  0.37
 3     0.13  0.26  0.23   0.2  0.18  0.12  0.11   0.1  0.13
 4      2.2   6.6   7.9   4.2   2.9   3.4     3   2.5   2.2
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 4316    70    66    85    67    60    61    60    59   308
 4317    83   106   105    60    62    58    75    18   311
 4318   3.7   2.8   3.8   4.1   3.2   3.1   2.8   2.3   2.6
 4319     2     2   1.7     3   2.9   2.7   2.8   1.3   1.7

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       15    17    20    22    22    22    22    22    21
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.78  0.74  0.59  0.52  0.41   0.4  0.37  0.37  0.47
 3     0.26  0.23   0.2  0.18  0.12  0.11   0.1  0.13  0.14
 4      6.6   7.9   4.2   2.9   3.4     3   2.5   2.2   2.5
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8     2
 4316    66    85    67    60    61    60    59   308   327
 4317   106   105    60    62    58    75    18   311    52
 4318   2.8   3.8   4.1   3.2   3.1   2.8   2.3   2.6   1.3
 4319     2   1.7     3   2.9   2.7   2.8   1.3   1.7   0.7

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       17    20    22    22    22    22    22    21    19
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.74  0.59  0.52  0.41   0.4  0.37  0.37  0.47  0.69
 3     0.23   0.2  0.18  0.12  0.11   0.1  0.13  0.14  0.23
 4      7.9   4.2   2.9   3.4     3   2.5   2.2   2.5   2.3
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8   1.8   1.8   1.8   1.8     2   2.1
 4316    85    67    60    61    60    59   308   327    21
 4317   105    60    62    58    75    18   311    52    54
 4318   3.8   4.1   3.2   3.1   2.8   2.3   2.6   1.3     1
 4319   1.7     3   2.9   2.7   2.8   1.3   1.7   0.7   0.4

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       20    22    22    22    22    22    21    19    17
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.59  0.52  0.41   0.4  0.37  0.37  0.47  0.69  0.56
 3      0.2  0.18  0.12  0.11   0.1  0.13  0.14  0.23  0.18
 4      4.2   2.9   3.4     3   2.5   2.2   2.5   2.3   2.1
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8   1.8   1.8   1.8     2   2.1     2
 4316    67    60    61    60    59   308   327    21   100
 4317    60    62    58    75    18   311    52    54   121
 4318   4.1   3.2   3.1   2.8   2.3   2.6   1.3     1   1.5
 4319     3   2.9   2.7   2.8   1.3   1.7   0.7   0.4   1.1

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       22    22    22    22    22    21    19    17    16
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.52  0.41   0.4  0.37  0.37  0.47  0.69  0.56  0.45
 3     0.18  0.12  0.11   0.1  0.13  0.14  0.23  0.18  0.12
 4      2.9   3.4     3   2.5   2.2   2.5   2.3   2.1   1.9
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8   1.8   1.8     2   2.1     2   1.9
 4316    60    61    60    59   308   327    21   100   109
 4317    62    58    75    18   311    52    54   121    97
 4318   3.2   3.1   2.8   2.3   2.6   1.3     1   1.5     1
 4319   2.9   2.7   2.8   1.3   1.7   0.7   0.4   1.1   1.4

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       22    22    22    22    21    19    17    16    15
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.41   0.4  0.37  0.37  0.47  0.69  0.56  0.45  0.38
 3     0.12  0.11   0.1  0.13  0.14  0.23  0.18  0.12   0.1
 4      3.4     3   2.5   2.2   2.5   2.3   2.1   1.9   1.5
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8   1.8     2   2.1     2   1.9   1.9
 4316    61    60    59   308   327    21   100   109   108
 4317    58    75    18   311    52    54   121    97   107
 4318   3.1   2.8   2.3   2.6   1.3     1   1.5     1   1.7
 4319   2.7   2.8   1.3   1.7   0.7   0.4   1.1   1.4   1.3

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       22    22    22    21    19    17    16    15    15
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2      0.4  0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35
 3     0.11   0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09
 4        3   2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8   1.8     2   2.1     2   1.9   1.9   1.9
 4316    60    59   308   327    21   100   109   108   114
 4317    75    18   311    52    54   121    97   107   118
 4318   2.8   2.3   2.6   1.3     1   1.5     1   1.7   1.5
 4319   2.8   1.3   1.7   0.7   0.4   1.1   1.4   1.3   1.6

 [4320 rows x 9 columns],
          0     1     2     3     4     5     6     7     8
 0       22    22    21    19    17    16    15    15    15
 1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
 2     0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36
 3      0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1
 4      2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8
 ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
 4315   1.8   1.8     2   2.1     2   1.9   1.9   1.9     2
 4316    59   308   327    21   100   109   108   114   108
 4317    18   311    52    54   121    97   107   118   100
 4318   2.3   2.6   1.3     1   1.5     1   1.7   1.5     2
 4319   1.3   1.7   0.7   0.4   1.1   1.4   1.3   1.6   1.8

 [4320 rows x 9 columns]]

In [97]:
# review "Python for Data Analysis" concat操作
# train_x and train_y are the type of Dataframe
# 取出 PM2.5 的数据，训练集中一共有 240 天，每天取出 15 组 含有 9 个特征 和 1 个标签的数据，共有 240*15*9个数据
train_x = pd.concat(train_x) # (3600, 9) Dataframe类型
train_y = pd.concat(train_y)

In [116]:
# 竖着拼接，特征（列数）是9，行数是15*4320=64800
train_x.shape

(64800, 9)

In [98]:
# 将str数据类型转换为 numpy的 ndarray 类型
train_y = np.array(train_y, float)
test_x = np.array(test_x, float)
# print(train_x.shape, train_y.shape)

In [99]:
# 进行标准缩放，即数据归一化
ss = StandardScaler()

In [100]:
# 进行数据拟合
ss.fit(train_x)
# 进行数据转换
train_x = ss.transform(train_x)

In [101]:
# 定义评估函数
# 计算均方误差（Mean Squared Error，MSE）
# r^2 用于度量因变量的变异中 可以由自变量解释部分所占的比例 取值一般为 0~1
def r2_score(y_true, y_predict):
    # 计算y_true和y_predict之间的MSE
    MSE = np.sum((y_true - y_predict) ** 2) / len(y_true)
    # 计算y_true和y_predict之间的R Square
    return 1 - MSE / np.var(y_true)

In [102]:
# 线性回归
class LinearRegression:

    def __init__(self):
        # 初始化 Linear Regression 模型
        self.coef_ = None
        self.intercept_ = None
        self._theta = None

    def fit_normal(self, X_train, y_train):
        # 根据训练数据集X_train, y_train训练Linear Regression模型
        assert X_train.shape[0] == y_train.shape[0], \
            "the size of X_train must be equal to the size of y_train"

        # 对训练数据集添加 bias
        X_b = np.hstack([np.ones((len(X_train), 1)), X_train])
        self._theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_train)

        self.intercept_ = self._theta[0]
        self.coef_ = self._theta[1:]

        return self

    def fit_gd(self, X_train, y_train, eta=0.01, n_iters=1e4):
        '''
        :param X_train: 训练集
        :param y_train: label
        :param eta: 学习率
        :param n_iters: 迭代次数
        :return: theta 模型参数
        '''
        # 根据训练数据集X_train, y_train, 使用梯度下降法训练Linear Regression模型
        assert X_train.shape[0] == y_train.shape[0], \
            "the size of X_train must be equal to the size of y_train"

        # 定义损失函数
        def J(theta, X_b, y):
            try:
                return np.sum((y - X_b.dot(theta)) ** 2) / len(y)
            except:
                return float('inf')
        # 对损失函数求导
        def dJ(theta, X_b, y):
            return X_b.T.dot(X_b.dot(theta) - y) * 2. / len(y)

        def gradient_descent(X_b, y, initial_theta, eta, n_iters=1e4, epsilon=1e-8):
            '''
            :param X_b: 输入特征向量
            :param y: lebel
            :param initial_theta: 初始参数
            :param eta: 步长
            :param n_iters: 迭代次数
            :param epsilon: 容忍度
            :return:theta：模型参数
            '''
            theta = initial_theta
            cur_iter = 0

            while cur_iter < n_iters:
                gradient = dJ(theta, X_b, y)
                last_theta = theta
                theta = theta - eta * gradient
                if (abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):
                    break
                cur_iter += 1
            return theta

        X_b = np.hstack([np.ones((len(X_train), 1)), X_train])
        initial_theta = np.zeros(X_b.shape[1]) # 初始化theta
        self._theta = gradient_descent(X_b, y_train, initial_theta, eta, n_iters)
        self.intercept_ = self._theta[0]
        self.coef_ = self._theta[1:]
        return self

    def predict(self, X_predict):
        # 给定待预测数据集X_predict，返回表示X_predict的结果向量
        assert self.intercept_ is not None and self.coef_ is not None, \
            "must fit before predict!"
        assert X_predict.shape[1] == len(self.coef_), \
            "the feature number of X_predict must be equal to X_train"
        X_b = np.hstack([np.ones((len(X_predict), 1)), X_predict])
        return X_b.dot(self._theta)

    def score(self, X_test, y_test):
        # 根据测试数据集 X_test 和 y_test 确定当前模型的准确度
        y_predict = self.predict(X_test)
        return r2_score(y_test, y_predict)

    def __repr__(self):
        return

In [108]:
# 模型训练
LR = LinearRegression().fit_gd(train_x, train_y)
# 评分
LR.score(train_x, train_y)
# 预测
result = LR.predict(test_x)

# 结果保存
sampleSubmission = pd.read_csv(path + 'sampleSubmission.csv')
# sampleSubmission['value'] = result
# sampleSubmission.to_csv(path + 'result.csv')

ValueError: Length of values does not match length of index